### ISSUE TITLE
How shake animation and audio work?

### ISSUE THREAD

**Issue by phuanh004** [cse110-sp23-group3/8-ball#14]
Related to #12, Is it supposed to work on the `no` answer only, or the `yes` as well? 

Since, the animation looks like only for `no`, should we split it into a hashtable with, true/ false value?

For example:
```js
{
"It is certain.": true,
"It is decidedly so.": true,
"My sources say no.": false,
}
```

**Comment by lemangomeister** [comment]
Are you saying that the animation only works if the answer some variation of `no` ? I currently have Jiaen's on my local and it works for variations of `yes`

**Comment by phuanh004** [comment]
> Are you saying that the animation only works if the answer some variation of `no` ? I currently have Jiaen's on my local and it works for variations of `yes`

My bad, I think it is working for both but Idk if ppl want to split them out

**Comment by nsyousef** [comment]
I think we should play the shaking animation for both yes and no. With physical 8-balls, people generally ask it a question and shake it to get it to tell them the answer.

**Comment by phuanh004** [comment]
Yeah, it makes sense.
