### ISSUE TITLE
Feature Request - Text Box

### ISSUE THREAD

**Issue by lemangomeister** [cse110-sp23-group3/8-ball#2]
Add a text box

**Comment by yujiaen1999** [comment]
I'm not sure what the text box should look like, can you describe it more?

**Comment by lemangomeister** [comment]
> I'm not sure what the text box should look like, can you describe it more?

There really isn't a specific look that's required. I think as long as it is a functioning text box, then that's fine. Anything else beyond that is just aesthetics.

**Comment by nsyousef** [comment]
I have set the button to become disabled/greyed out when the answer is generated. It becomes re-enabled once the answer shows up on screen. I have found this eliminates a lot of bugs that occur if the user spam-clicks the button. So you may want to include a `:disabled` pseudo-class when styling the button.

**Comment by phuanh004** [comment]
> I have set the button to become disabled/greyed out when the answer is generated. It becomes re-enabled once the answer shows up on screen. I have found this eliminates a lot of bugs that occur if the user spam-clicks the button. So you may want to include a `:disabled` pseudo-class when styling the button.

Yep, I'll create another issue for styling this button.
Since we already have a text field, and not sure what is the purpose of the textbox. I close this issue.
