### ISSUE TITLE
Feature Request - Save Previous Question

### ISSUE THREAD

**Issue by lemangomeister** [cse110-sp23-group3/8-ball#5]
This is so that asking the same question prompts a text that tells the user to change the current question.

**Comment by phuanh004** [comment]
#2

**Comment by nsyousef** [comment]
I just realized this might not make too much sense if you happen to get the "concentrate and ask again" response. It seems to me like it would be weird to be told to "concentrate and ask again" but then when you click the button, it tells you to change the current question.

There are a few ways we could resolve this. We could change the "concentrate and ask again" response slightly to something that signifies asking again but with different wording. We could also make the app keep track of when the previous response is "concentrate and ask again" and allow the user to submit the same question again only when that response is given.

**Comment by phuanh004** [comment]
#16

**Comment by phuanh004** [comment]
Sorry for closing the wrong issue, Nick.

I think that you could create another branch from the new `main` instead of working on the old code since I changed it a lot.
On your code, I commented on that on #18, check it.

**Comment by nsyousef** [comment]
Ok, yeah. I actually figured out how to load the updated code from main into the Nick branch. I am currently working on implementing the feature with the updated code. I will make a new pull request when it is ready. That one should not have as many conflicts. We can ignore this one.

**Comment by phuanh004** [comment]
Since it is just a few lines of code, creating a new one from the `main` is easier than you merge and trying to solve all the conflicts. For example, the old `script.js` and many unnecessary commits from your current branch, when merging to the main. 
If you want to work on your own code, the `fork` option is much better than creating a new branch for a single person. Try not to personalize a branch.

**Comment by nsyousef** [comment]
Alright. Well, it is kind of too late. I already added the feature in the Nick branch and got it working. But I'll know for next time. Sorry, I am not super well-versed in git/github so I am kind of learning as I go.

The feature is ready in the nick branch. I will make a new pull request now.
