### ISSUE TITLE
Feature Request - navbar

### ISSUE THREAD

**Issue by dolivares11** [cse110-sp23-group3/8-ball#9]
The navbar can allow us to navigate to different types of magic 8 balls if we wanted to have a variety. I was able to generate a webpage that included a navbar with ChatGPT that was functional and simply a quick copy/paste.

**Comment by phuanh004** [comment]
This sounds cool. Are there any other types of 8-ball that you can think of as examples?

**Comment by dolivares11** [comment]
I didn’t have any in specific, but we could also just implement a home page.

**Comment by phuanh004** [comment]
Unless we have a good navbar for one page, I don't think we need one since it will break the source link. For example, I am now using the relative link for the audio file. It won't work with routing stuff.

```js
const AUDIO_FILE = "assets/media/mystical8ball.mp3"
```

P/S: Reopen if having more info
